### ISSUE TITLE
Can't start. "EPERM: operation not permitted, symlink"

### ISSUE THREAD

**Issue by valnaumov** [fusepilot/create-cep-extension#31]
### Description

Can't run npm start.

### Actual behavior

```
create-cep-extension-scripts start

C:\temp\cep-webpack-latest\my-ext\node_modules\create-cep-extension-scripts\scripts\start.js:17
  throw err
  ^

Error: EPERM: operation not permitted, symlink 'C:\temp\cep-webpack-latest\my-ext\extendscript' -> 'C:\temp\cep-webpack-latest\my-ext\build/extendscript'
    at Object.symlinkSync (fs.js:927:3)
    at symlinkExtendscriptFolder (C:\temp\cep-webpack-latest\my-ext\node_modules\create-cep-extension-scripts\scripts\cep.js:77:17)
    at Object.compile (C:\temp\cep-webpack-latest\my-ext\node_modules\create-cep-extension-scripts\scripts\cep.js:198:3)
    at run (C:\temp\cep-webpack-latest\my-ext\node_modules\create-cep-extension-scripts\scripts\start.js:60:7)
    at detect.then.port (C:\temp\cep-webpack-latest\my-ext\node_modules\create-cep-extension-scripts\scripts\start.js:105:5)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-ext@0.1.0 start: `create-cep-extension-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-ext@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-12-25T07_18_36_842Z-debug.log
```

debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.5.0
3 info using node@v11.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-ext@0.1.0~prestart: my-ext@0.1.0
6 info lifecycle my-ext@0.1.0~start: my-ext@0.1.0
7 verbose lifecycle my-ext@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-ext@0.1.0~start: PATH: C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\temp\cep-webpack-latest\my-ext\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\photo_tools;c:\Program Files\dev_tools\openssl\;C:\Program Files\ffmpeg\bin;C:\Program Files\Adobe\Adobe After Effects CC 2017\Support Files;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;c:\Program Files\MySQL\MySQL Server 5.7\bin\;c:\Program Files\dev_tools\grails-3.3.4\\bin;c:\Program Files\ConEmu\;C:\Program Files\dev_tools\gradle-4.9\bin;C:\Program Files\dev_tools\apache-maven-3.3.9\bin;C:\Program Files\PostgreSQL\9.6\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;c:\Program Files (x86)\Groovy\groovy-2.4.12\\bin;C:\Program Files\Java\jdk1.8.0_181\bin;c:\Program Files\PostgreSQL\9.6\;C:\Program Files\Git\cmd;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;c:\altera\91sp2\quartus\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\nodejs\;c:\Program Files (x86)\GnuPG\bin\;c:\Program Files\dev_tools\apache-maven-3.3.9\bin\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\.lein\bin;C:\Users\User\AppData\Roaming\npm
9 verbose lifecycle my-ext@0.1.0~start: CWD: C:\temp\cep-webpack-latest\my-ext
10 silly lifecycle my-ext@0.1.0~start: Args: [ '/d /s /c', 'create-cep-extension-scripts start' ]
11 silly lifecycle my-ext@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle my-ext@0.1.0~start: Failed to exec start script
13 verbose stack Error: my-ext@0.1.0 start: `create-cep-extension-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid my-ext@0.1.0
15 verbose cwd C:\temp\cep-webpack-latest\my-ext
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v11.5.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-ext@0.1.0 start: `create-cep-extension-scripts start`
22 error Exit status 1
23 error Failed at the my-ext@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls create-cep-extension-scripts` (if you haven’t ejected): create-cep-extension-scripts@1.0.0-y.0
2. `node -v`: v11.5.0
3. `npm -v`: v11.5.0
Windows 10

**Comment by hanchengz** [comment]
I have met this like you,and how can you deal with this?

**Comment by premiereonscript** [comment]
Running VS Code as admin on windows solved this issue for me
