### ISSUE TITLE
I get a failure when trying to archive as a zip

### ISSUE THREAD

**Issue by sgdovev** [fusepilot/create-cep-extension#59]
Can you help me figure out what's going on?

```
> react-imago@0.1.0 archive /Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago
> create-cep-extension-scripts archive

Signing and archiving...

Error: Command failed: "/Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/node_modules/zxp-provider/bin/osx/ZXPSignCmd" -sign /Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/build /Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/archive/My-CEP-Extension-0.1.0.zxp certificate.p12 certificate-password 
Usage:
    ZXPSignCmd -sign <inputDirectory> <outputZxp> <p12> <p12Password> [options]
	options:
		-tsa <timestampURL> - will attempt to timestamp the ZXP using supplied timestamp server. For example, https://timestamp.geotrust.com/tsa

    ZXPSignCmd -sign <inputDirectory> <outputZxp> -s <identity> [options]
	options:
		-keychain <filename> - identity is only looked-for in the specific keychain given

		-tsa <timestampURL> - will attempt to timestamp the ZXP using supplied timestamp server. For example, https://timestamp.geotrust.com/tsa

    ZXPSignCmd -verify <zxp>|<extensionRootDirectory> [options]
	options:
		-certInfo - will print out information about certificates (including timestamp and certificate revocation information)
		-skipOnlineRevocationChecks - will skip online checks for certificate revocation (certificate revocation checks only happen with -certInfo flag set)
		-addCerts <certificate1> <certificate2>... - will verify certificate chain and assess whether or not DER encoded certificates passed in are included

    ZXPSignCmd -selfSignedCert <countryCode> <stateOrProvince> <organization> <commonName> <password> <outputPath.p12> [options]
	options: 
		-locality <locality> -orgUnit <orgUnit> -email <email> -validityDays <validityDays> - are optional attributes for self-signed p12 certificates


    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: '"/Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/node_modules/zxp-provider/bin/osx/ZXPSignCmd" -sign /Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/build /Users/bnick/Library/Application Support/Adobe/CEP/extensions/react-imago/archive/My-CEP-Extension-0.1.0.zxp certificate.p12 certificate-password '
}

```

**Comment by greg-wakefield** [comment]
A year and a bit late but I just had this issue. It's because of the spaces in the path name. In your case 'Application Support'. You'll need to put the root folder somewhere it's path doesn't have them.
